### ISSUE TITLE
Support legacy links

### ISSUE THREAD

**Issue by mojoaxel** [visjs/www.visjs.org#2]
The following links should also work in newer versions of the site:
- [ ] http://visjs.org/download/vis.zip
- [x] http://visjs.org/docs/network/
- [x] https://visjs.org/docs/network/
- [x] https://visjs.org/network_examples.html
- [x] http://visjs.org/docs/network/interaction.html#

**Comment by codenoid** [comment]
yup, too many broken link

**Comment by mojoaxel** [comment]
> should we link the old site from the new one, like: Looking for the <a>previous website</a> ?

Yeah, maybe..I'll figure something out.

**Comment by mojoaxel** [comment]
All links to `/docs/` and the examples overviews hab now a fallback. I think this is enough!
If anybody has problems please let me know!

**Comment by codenoid** [comment]
lol, i just start working on it, thankyou <3

**Comment by mojoaxel** [comment]
> lol, i just start working on it, thankyou <3

Lol! Feel free to improve the pages!

This is how the redirect pages look atm:
![image](https://user-images.githubusercontent.com/600565/61996435-8e444d00-b094-11e9-84f9-f69f587a1d74.png)

**Comment by codenoid** [comment]
i don't know, please take a look

[https://visjs.org/docs/data/dataset.html#Methods](https://visjs.org/docs/data/dataset.html#Methods)

should not missing

**Comment by mojoaxel** [comment]
> https://visjs.org/docs/data/dataset.html#Methods

fixed with 2e905dbfdda253c9df81a1e7b8eeb6a10fa3d7a2
