### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by tbremard** [visjs/www.visjs.org#21]
see attached file
https://visjs.github.io/vis-timeline/examples/graph2d/

![Screen_2020-12-0218 29 43803](https://user-images.githubusercontent.com/36224228/100909067-8be5d480-34cc-11eb-95be-e05abaaaf1bd.png)

**Comment by mojoaxel** [comment]
closing as duplicate of https://github.com/visjs/vis-timeline/issues/652
