### ISSUE TITLE
integrate browserstack

### ISSUE THREAD

**Issue by mojoaxel** [visjs/www.visjs.org#6]
I asked for free browserstack support for visjs and I got an OK: :+1: 

> BrowserStack loves open source and has sponsored thousands of projects. Here is more information about our offering and activation process.
>
> What you get for free: Unlimited manual and automated testing for open source websites and mobile apps. Full platform access to Live, Automate, App Live and App Automate. Total of 5 user licenses and parallels.
>
> What we request in return: Give us a shoutout on your GitHub project page or website. Post and hyperlink our [attached logo](https://bstacksupport.zendesk.com/attachments/token/BmcQcBReYKYGAnyslphrZKyRL/?name=browserstack-logo-600x315.png), and a line about how you use BrowserStack. We are counting on you to help us spread the word to the open-source community.
>
> Next steps:
> 1. [Sign up for a BrowserStack free trial account.](https://www.browserstack.com/users/sign_up)
> 2. [Add a status badge to your project](https://www.browserstack.com/automate/status-badges), if you're using Automate.
> 3. Send us your free trial account email ID and the updated GitHub page. 
>
> We look forward to being a part of your open source journey. Have a great day!

We could use our @vis-bot account for this.
@visjs/maintainer What do you think? Sould we integrate browserstack automated tests?

**Comment by Thomaash** [comment]
Looks great.

**Comment by mojoaxel** [comment]
https://www.browserstack.com/blog/3-part-guide-faster-regression-testing/

**Comment by mojoaxel** [comment]
I'm working on this!
- [x] Add browserstack-logo to the website (see #7)
- [ ] Send account info to browserstack to get a free license.
- [ ] Integrate browserstack in the CI (see https://www.browserstack.com/automate/continuous-integration)

**Comment by Thomaash** [comment]
Hi @mojoaxel,

did this work out? Can we use it?

**Comment by mojoaxel** [comment]
No, I didn't get any reply. I'll start a new conversation with them. Hopefully it will work out.

**Comment by mojoaxel** [comment]
Today I contact browserstack again. Let's see if something happens this week:
> Hi there!
> 
> I'm one of the the maintainers of visjs, a open-source charting library.
> Sometimes we need to test specific browsers like IE11. I would be
> wonderful if you would support us by giving us free access to your IE
> machines.
> 
> We already had contact with you (Ticket #222223) but sadly the
> conversation could not be continued (for some technical reason)!?
> 
> We already added a prominent supporter-link to browserstack to our
> Website: https://visjs.org/#supporters
> 
> We also created an account. Its called "visjsbot" (visjsbot@gmail.com)
> and it will be used by 2-3 maintainers.
> 
> We need browserstack mainly to manually test out library in Internet
> Explorer. So we don't expect to create a big load on your services 
> 
> We don't plan to use Automate, yet so we could not add a badge to the
> README files of our multiple projects but we will maybe do that in the
> future.
> 
> We would be very happy it you would consider supporting our 100%
> OpenSource work.
> 
> Hope to here from you soon!
> 
> Alex aka. mojoaxel
> and others maintainers of vis.js

**Comment by yotamberk** [comment]
👍

**Comment by mojoaxel** [comment]
browserstack is not answering...
