### ISSUE TITLE
Ads via Carbon

### ISSUE THREAD

**Issue by mojoaxel** [visjs/www.visjs.org#9]
We have been offered to integrate ads [before](https://github.com/almende/vis/issues/3648).
We should discuss if we want to integrate a banner from www.carbonads.net on our langingpage and maybe even the documentation pages.

The money would land directly in our [opencollective](http://opencollective.com/visjs).

@visjs/maintainer Please comment on that!

**Comment by mojoaxel** [comment]
This is how it could look:
![image](https://user-images.githubusercontent.com/600565/66077155-ac7c6c80-e55f-11e9-9165-4e0d9872437e.png)

**Comment by Thomaash** [comment]
I say let's do it. It would be nice (and easier with ad revenue) to turn this into a part time job.

**Comment by mojoaxel** [comment]
Maybe @sayzlim is still at carbon and can help?

**Comment by sayzlim** [comment]
I’ll have a look at it tonight and submit a PR for review.

**Comment by mojoaxel** [comment]
@sayzlim thx, but my question is more what we would have to do to get a carbon account.

**Comment by sayzlim** [comment]
@mojoaxel my bad, I thought it was about the integration. I’ve sent the account details to your email address. You can add more members so they can check out the dashboard.

Do you want to me to create a PR with the ad code integrated? Also, we want to the payment sent to vis.js collective automatically right?

**Comment by yotamberk** [comment]
I'm for this! 
It can be a great way to get some extra cash for the opencollective account.

**Comment by sayzlim** [comment]
Please kindly review this: https://github.com/visjs/www.visjs.org/pull/12

Let me know if you wish to change or update the ad format.

**Comment by sayzlim** [comment]
Thanks for merging the PR @Thomaash. I’ve informed Pia from Open Collective that the ad is live and they will take care of the rest of sending the earnings to vis.js collective every month.

**Comment by mojoaxel** [comment]
@sayzlim Thanks for your help!

**Comment by mojoaxel** [comment]
@sayzlim What do you say? does it also make sense to integrate these ads also in the docs pages? e.g. here: https://visjs.github.io/vis-timeline/docs/timeline/

**Comment by sayzlim** [comment]
@mojoaxel all the docs are still pointing to the archived website. Do you want me to move it over before integrating Carbon?

**Comment by sayzlim** [comment]
@mojoaxel you can copy the code from the homepage to these docs. You can refer to https://codepen.io/collection/AyEoKk/ for some example CSS that could fit the docs layout better.

**Comment by piamancini** [comment]
Hey all! As we receive the funds in the [Open Source Collective](https//:oscollective.org) paypal account we'll add them to your collective. Feel free to at me here or find me in slack if there are any question. Cheers!
